# Generated by Django 3.0 on 2020-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='tel1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='tel2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='tel3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tel',
            field=models.CharField(max_length=64),
        ),
    ]
