# Generated by Django 3.0 on 2020-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200925_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='working_hours',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Время работы'),
        ),
    ]
