# Generated by Django 3.0 on 2020-09-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200925_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Населенный пункт'),
        ),
    ]
