# Generated by Django 3.0 on 2020-09-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200925_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesConf',
        ),
        migrations.DeleteModel(
            name='ServicesPayment',
        ),
        migrations.DeleteModel(
            name='ServicesStuff',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Пункт правовой инофрмации (FAQ)', 'verbose_name_plural': 'Пункты правовой инофрмации (FAQ)'},
        ),
        migrations.AlterModelOptions(
            name='faqlist',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='helpfile',
            options={'verbose_name': 'Файл первой медицинской помощи'},
        ),
        migrations.AlterModelOptions(
            name='organizationservices',
            options={'verbose_name': 'Услуги организации'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
