# Generated by Django 3.0 on 2020-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20201018_1634'),
        ('cms', '0007_backcall_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParetnForSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_link', models.ManyToManyField(blank=True, null=True, related_name='left_sidebar_links', to='page.Page')),
            ],
        ),
    ]
