# Generated by Django 3.0 on 2020-10-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_paretnforsidebar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParetnForSidebar',
        ),
    ]
