# Generated by Django 3.0 on 2020-10-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_examplecmsbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleCMSBase',
        ),
    ]
