# Generated by Django 3.0 on 2020-10-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_delete_examplecmsbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigthSidebarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текстовая информация')),
            ],
            options={
                'verbose_name': 'Полезная информация в правом сайдбаре',
                'verbose_name_plural': 'Полезная информация в правом сайдбаре',
            },
        ),
    ]
