# Generated by Django 3.0 on 2020-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_rigthsidebarinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqlist',
            name='text',
            field=models.TextField(help_text='список: &ltul&gt &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt\n         &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt &lt/ul&gt', verbose_name='Содержимое статьи'),
        ),
    ]
