version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx_chat_orig
    restart: unless-stopped
    networks:
      nginx_net:
    #networks:
    #  - botnet
    ports:
      - "80:80"
      - "443:443"
#      - 8000:8000
#      - 8200:8200
#      - 8300:8300
    volumes:
      - ./nginx_abuse/abuse:/src  
      - ./rel_kids/:/src2
      - ./ButonBotDjango/ButonBotDjango:/src3
      - ./ButonBotDjango/config/nginx:/etc/nginx/conf.d
      - ./ButonBotDjango/logs:/logs
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # - /var/www/httpd-cert/www-root:/etc/ssl        
    depends_on:
      - web3
      - web2
      - web1
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    # Новый контейнер, который запуститься вместе с nginx
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    # Образ берется с docker hub
    networks:
      nginx_net:
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # Подключаем к той-же сети, что и остальные контейнеры
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  bot:
    build:
      context: .
      dockerfile: ButonBotDjango/compose/django/Dockerfile
    container_name: telegram-bot_orig
    restart: always
    networks:
      nginx_net:
    #    networks:
    #      - botnet
    volumes:
      - ./ButonBotDjango/ButonBotDjango:/src3
    expose:
      - 8300
    command: sh -c
      "echo hello world && python3 help_bot/telega.py"

  web3:
    build:
      context: .
      dockerfile: ./ButonBotDjango/compose/django/Dockerfile
    networks:
      nginx_net:
    container_name: chatbot
    restart: always
    volumes:
      - ./ButonBotDjango/ButonBotDjango:/src3
    #    networks:
    #      - botnet
    #    expose:
    #      - "8000"
    #      command: sh -c
    #        "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    # new
    expose:
      - 8000
    # new
    command: bash -c
      "python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000"

  web1:
    build:
      context: .
      dockerfile: ./nginx_abuse/Dockerfile
    networks:
      nginx_net:
    container_name: abuse
    volumes:
      - ./nginx_abuse/abuse:/src
    expose:
      - 8200
    tty: true    
    command: python3 manage.py runserver 0.0.0.0:8200


  web2:
    build:
      context: .
      dockerfile: ./rel_kids/Dockerfile
    networks:
      nginx_net:
    container_name: pomogutkids
    volumes:
      - ./rel_kids:/src2
    expose:
      - 8400
    tty: true    
    command: python3 manage.py runserver 0.0.0.0:8400
    

networks:
  botnet:
    driver: bridge
    driver_opts:
      "com.docker.network.bridge.enable_icc": "true"
      "com.docker.network.bridge.enable_ip_masquerade": "true"
      "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0"
      "com.docker.network.bridge.name": "br0"
      "com.docker.network.driver.mtu": "1500"




  # Блок для объявления внутренних docker сетей, которые запустятся с этим файлом
  nginx_net:
    # Название сети для этого контейнера
    name: nginx_net
    # Название сети для внешних контейнеров

    # Название сети для внешних контейнеров

