# Generated by Django 3.0.8 on 2020-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='needhelp',
            name='website',
            field=models.CharField(blank=True, help_text="в формате: 'example.com example2.com test.example2.com'", max_length=512, null=True, verbose_name='на каких сайтах бот включен'),
        ),
    ]
