version: "3"


services:
  web:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_pomogutkids
    volumes:
      - .:/src
    # ports:
    #   - "8000:8000"
    tty: true    
    command: python3 manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx
    container_name: kids_nginx
    ports:
      - 8000:8000
    depends_on:
      - web
    volumes:
      - .:/src
      - ./config:/etc/nginx/conf.d