# Generated by Django 3.0 on 2020-09-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footersection_set', to='page.Page')),
            ],
            options={
                'verbose_name': 'footer section',
                'verbose_name_plural': 'footer sections',
                'db_table': 'page_page_footersection',
                'ordering': ['ordering'],
                'permissions': [],
                'abstract': False,
            },
        ),
    ]
