# Generated by Django 3.0 on 2020-09-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_footersection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accordeonarticle',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Правовая информация', 'verbose_name_plural': 'Правовая информация'},
        ),
        migrations.AlterModelOptions(
            name='articlepicture',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
        migrations.AlterModelOptions(
            name='calendararticle',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Статья с календарем', 'verbose_name_plural': 'Стати с календарем'},
        ),
        migrations.AlterModelOptions(
            name='employmentarticle',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Трудоустройство', 'verbose_name_plural': 'Трудоустройство'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksection',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Секция обратной связи', 'verbose_name_plural': 'Секция обратной связиs'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'секция Footer', 'verbose_name_plural': 'секция Footers'},
        ),
        migrations.AlterModelOptions(
            name='orgsection',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Секция организаций', 'verbose_name_plural': 'Секция организаций'},
        ),
        migrations.AlterModelOptions(
            name='participantwidget',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Участники проекта', 'verbose_name_plural': 'Участники проекта'},
        ),
        migrations.AlterModelOptions(
            name='quizwidget',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='standartarticle',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Стандартная статья', 'verbose_name_plural': 'Стандартные статья'},
        ),
    ]
