# Generated by Django 3.0 on 2020-10-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_leftsidebarwidget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leftsidebarwidget',
            old_name='left_link',
            new_name='cross_link',
        ),
    ]
