# Generated by Django 3.0 on 2020-10-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20201018_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftsidebarwidget',
            name='alt_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативная ссылка'),
        ),
        migrations.RemoveField(
            model_name='leftsidebarwidget',
            name='cross_link',
        ),
        migrations.AddField(
            model_name='leftsidebarwidget',
            name='cross_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_sidbar_link', to='page.Page'),
        ),
    ]
