# Generated by Django 3.0 on 2020-10-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20201018_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeftSidebarWidget',
        ),
    ]
