# Generated by Django 3.0 on 2020-10-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_delete_leftsidebarwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartarticle',
            name='link_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
    ]
