# Generated by Django 3.0 on 2020-10-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_standartarticle_link_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standartarticle',
            old_name='link_title',
            new_name='alt_title',
        ),
        migrations.AddField(
            model_name='accordeonarticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='calendararticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='employmentarticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='participantwidget',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
    ]
