# Generated by Django 3.0 on 2020-10-18 13:32

from django.db import migrations, models
import django.db.models.deletion
import feincms.module.page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20201018_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftSidebardSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('cross_link', models.NullBooleanField(verbose_name=feincms.module.page.models.Page)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftsidebardsection_set', to='page.Page')),
            ],
            options={
                'verbose_name': 'Левый сайдбар',
                'verbose_name_plural': 'Левый сайдбарs',
                'db_table': 'page_page_leftsidebardsection',
                'ordering': ['ordering'],
                'permissions': [],
                'abstract': False,
            },
        ),
    ]
