# Generated by Django 3.0 on 2020-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_leftsidebardsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftsidebardsection',
            name='cross_link',
        ),
        migrations.AddField(
            model_name='leftsidebardsection',
            name='cross_link',
            field=models.ManyToManyField(blank=True, related_name='left_sidebar_links', to='page.Page'),
        ),
    ]
