# Generated by Django 3.0 on 2020-10-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_paretnforsidebar'),
        ('page', '0012_auto_20201018_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftsidebardsection',
            name='cross_link',
        ),
        migrations.RemoveField(
            model_name='leftsidebardsection',
            name='id',
        ),
        migrations.AddField(
            model_name='leftsidebardsection',
            name='paretnforsidebar_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.ParetnForSidebar'),
            preserve_default=False,
        ),
    ]
