# Generated by Django 3.0 on 2020-10-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20201019_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accordeonarticle',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='calendararticle',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='employmentarticle',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='participantwidget',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='standartarticle',
            name='alt_title',
        ),
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='page',
            name='translation_of',
            field=models.ForeignKey(blank=True, help_text='Leave this empty for entries in the primary language.', limit_choices_to={'language': 'ru'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.Page', verbose_name='translation of'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[('widgets/news_widget.html', 'Новость'), ('widgets/refactor_art.html', 'Отдельная статья')], default='widgets/news_widget.html', max_length=255, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='richtextcontent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richtextcontent_set', to='page.Page'),
        ),
        migrations.AlterModelTable(
            name='richtextcontent',
            table='page_page_richtextcontent',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
