# Generated by Django 3.0 on 2020-10-19 15:57

from django.db import migrations, models
import django.db.models.deletion
import feincms.contrib.fields
import feincms.extensions.base
import feincms.extensions.datepublisher
import feincms.module.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20201019_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='language',
        ),
        migrations.RemoveField(
            model_name='page',
            name='translation_of',
        ),
        migrations.AddField(
            model_name='accordeonarticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='calendararticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='employmentarticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='participantwidget',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AddField(
            model_name='standartarticle',
            name='alt_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Альтернативное наименование в левом сайдбаре'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[('widgets/refactor_art.html', 'Отдельная статья')], default='widgets/refactor_art.html', max_length=255, verbose_name='template'),
        ),
        migrations.AlterModelTable(
            name='richtextcontent',
            table='page_newspage_richtextcontent',
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(help_text='This title is also used for navigation menu items.', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(help_text='This is used to build the URL for this page', max_length=150, verbose_name='slug')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('override_url', models.CharField(blank=True, help_text="Override the target URL. Be sure to include slashes at the beginning and at the end if it is a local URL. This affects both the navigation and subpages' URLs.", max_length=255, verbose_name='override URL')),
                ('redirect_to', models.CharField(blank=True, help_text='Target URL for automatic redirects or the primary key of a page.', max_length=255, verbose_name='redirect to')),
                ('_cached_url', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255, verbose_name='Cached URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('template_key', models.CharField(choices=[('widgets/news_widget.html', 'Новость')], default='widgets/news_widget.html', max_length=255, verbose_name='template')),
                ('publication_date', models.DateTimeField(default=feincms.extensions.datepublisher.granular_now, verbose_name='publication date')),
                ('publication_end_date', models.DateTimeField(blank=True, help_text='Leave empty if the entry should stay active forever.', null=True, verbose_name='publication end date')),
                ('_ct_inventory', feincms.contrib.fields.JSONField(blank=True, editable=False, null=True, verbose_name='content types')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.NewsPage', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'newspage',
                'verbose_name_plural': 'newspages',
                'ordering': ['tree_id', 'lft'],
            },
            bases=(models.Model, feincms.extensions.base.ExtensionsMixin, feincms.module.mixins.ContentModelMixin),
        ),
        migrations.AlterField(
            model_name='richtextcontent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richtextcontent_set', to='page.NewsPage'),
        ),
    ]
