# Generated by Django 3.0 on 2020-10-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_newspage_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='test_category',
        ),
    ]
