# Generated by Django 3.0 on 2020-10-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_remove_newspage_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepicture',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlepicture_set', to='page.NewsPage'),
        ),
        migrations.AlterModelTable(
            name='articlepicture',
            table='page_newspage_articlepicture',
        ),
    ]
