# Generated by Django 3.0 on 2020-10-19 16:57

from django.db import migrations, models
import django.db.models.deletion
import feincms.contrib.fields
import feincms.contrib.richtext
import feincms.extensions.base
import feincms.extensions.datepublisher
import feincms.module.medialibrary.fields
import feincms.module.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0001_initial'),
        ('page', '0020_auto_20201019_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(help_text='This title is also used for navigation menu items.', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(help_text='This is used to build the URL for this page', max_length=150, verbose_name='slug')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('override_url', models.CharField(blank=True, help_text="Override the target URL. Be sure to include slashes at the beginning and at the end if it is a local URL. This affects both the navigation and subpages' URLs.", max_length=255, verbose_name='override URL')),
                ('redirect_to', models.CharField(blank=True, help_text='Target URL for automatic redirects or the primary key of a page.', max_length=255, verbose_name='redirect to')),
                ('_cached_url', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255, verbose_name='Cached URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('template_key', models.CharField(choices=[('widgets/news_widget.html', 'Новость')], default='widgets/news_widget.html', max_length=255, verbose_name='template')),
                ('publication_date', models.DateTimeField(default=feincms.extensions.datepublisher.granular_now, verbose_name='publication date')),
                ('publication_end_date', models.DateTimeField(blank=True, help_text='Leave empty if the entry should stay active forever.', null=True, verbose_name='publication end date')),
                ('_ct_inventory', feincms.contrib.fields.JSONField(blank=True, editable=False, null=True, verbose_name='content types')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.NewsPage', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'newspage',
                'verbose_name_plural': 'newspages',
                'ordering': ['tree_id', 'lft'],
            },
            bases=(models.Model, feincms.extensions.base.ExtensionsMixin, feincms.module.mixins.ContentModelMixin),
        ),
        migrations.CreateModel(
            name='RichTextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('text', feincms.contrib.richtext.RichTextField(blank=True, verbose_name='text')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richtextcontent_set', to='page.NewsPage')),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich texts',
                'db_table': 'page_newspage_richtextcontent',
                'ordering': ['ordering'],
                'permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlepicture_set', to='page.NewsPage')),
                ('picture', feincms.module.medialibrary.fields.MediaFileForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medialibrary.MediaFile', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
                'db_table': 'page_newspage_articlepicture',
                'ordering': ['ordering'],
                'permissions': [],
                'abstract': False,
            },
        ),
    ]
