# Generated by Django 3.0 on 2020-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_auto_20201019_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[('widgets/refactor_art.html', 'Отдельная статья'), ('base', 'Новость')], default='widgets/refactor_art.html', max_length=255, verbose_name='template'),
        ),
    ]
