# Generated by Django 3.0 on 2020-10-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_rigthsidebarinfo'),
        ('page', '0027_auto_20201020_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizwidget',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quizwidget',
            name='title',
        ),
        migrations.AlterField(
            model_name='accordeonarticle',
            name='link',
            field=models.ManyToManyField(blank=True, to='cms.Link', verbose_name='Добавить ссылку'),
        ),
        migrations.AlterField(
            model_name='employmentarticle',
            name='link',
            field=models.ManyToManyField(blank=True, to='cms.Link', verbose_name='Добавить ссылку'),
        ),
        migrations.AlterField(
            model_name='standartarticle',
            name='link',
            field=models.ManyToManyField(blank=True, to='cms.Link', verbose_name='Добавить ссылку'),
        ),
    ]
