# Generated by Django 3.0 on 2020-10-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_auto_20201021_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
