# Generated by Django 3.0 on 2020-10-21 15:46

from django.db import migrations, models
import django.db.models.deletion
import feincms.module.medialibrary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0001_initial'),
        ('page', '0029_auto_20201021_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='preview_img',
        ),
        migrations.RemoveField(
            model_name='page',
            name='source',
        ),
        migrations.AddField(
            model_name='newspage',
            name='preview_img',
            field=feincms.module.medialibrary.fields.MediaFileForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medialibrary.MediaFile', verbose_name='Выбрать картинку'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на источник'),
        ),
    ]
