# Generated by Django 3.0 on 2020-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_auto_20201021_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='template_key',
            field=models.CharField(choices=[('widgets/newspage.html', 'Новость')], default='widgets/newspage.html', max_length=255, verbose_name='template'),
        ),
    ]
