# Generated by Django 3.0 on 2020-11-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_auto_20201021_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('script', models.TextField(help_text='youtube > поделиться > "<>" > скопировать текст', verbose_name='встроить видео')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsvideo_set', to='page.NewsPage')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'db_table': 'page_newspage_newsvideo',
                'ordering': ['ordering'],
                'permissions': [],
                'abstract': False,
            },
        ),
    ]
