# Generated by Django 3.0 on 2020-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0032_newsvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendararticle',
            options={'ordering': ['ordering'], 'permissions': [], 'verbose_name': 'Статья с календарем мероприятий', 'verbose_name_plural': 'Стати с календарем мероприятий'},
        ),
        migrations.AlterField(
            model_name='calendararticle',
            name='list',
            field=models.TextField(blank=True, default='<li><p></li>', null=True),
        ),
        migrations.AlterField(
            model_name='calendararticle',
            name='text',
            field=models.TextField(help_text='список: &ltul&gt &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt\n         &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt &lt/ul&gt'),
        ),
        migrations.AlterField(
            model_name='employmentarticle',
            name='text',
            field=models.TextField(blank=True, help_text='список: &ltul&gt &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt\n         &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt &lt/ul&gt', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='standartarticle',
            name='text',
            field=models.TextField(blank=True, help_text='список: &ltul&gt &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt\n         &ltli&gt&ltp&gtТекст пункта списка&lt/li&gt &lt/ul&gt', null=True, verbose_name='Текст'),
        ),
    ]
