# Generated by Django 3.0 on 2020-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20201107_2053'),
        ('page', '0033_auto_20201107_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendararticle',
            name='link',
            field=models.ManyToManyField(blank=True, to='cms.Link', verbose_name='Добавить ссылку'),
        ),
    ]
